package ru.zch.gasstation.domain;

// Generated 06.03.2015 2:11:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PointTypesId generated by hbm2java
 */
@Embeddable
public class PointTypesId implements java.io.Serializable {
	private static final long serialVersionUID = -3215963633391192813L;
	
	private Integer pid;
	private Integer tid;
	
	public PointTypesId() {
	}


	public PointTypesId(Integer pid, Integer tid) {
		this.pid = pid;
		this.tid = tid;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "tid")
	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PointTypesId))
			return false;
		PointTypesId castOther = (PointTypesId) other;

		return ((this.getPid() == castOther.getPid()) || (this.getPid() != null && castOther.getPid() != null && this.getPid().equals(castOther.getPid()))) && 
			   ((this.getTid() == castOther.getTid()) || (this.getTid() != null && castOther.getTid() != null && this.getTid().equals(castOther.getTid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPid() == null ? 0 : this.getPid().hashCode());
		result = 37 * result + (getTid() == null ? 0 : this.getTid().hashCode());
		return result;
	}

}
