package ru.zch.gasstation.domain;

// Generated 06.03.2015 2:11:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vote generated by hbm2java
 */
@Entity
@Table(name = "vote", catalog = "gasstation")
public class Vote implements java.io.Serializable {
	private static final long serialVersionUID = 546943524839322184L;
	
	private Integer id;
	private Point point;
	private Device device;
	private Integer vote;

	public Vote() {
	}

	public Vote(Point point, Device device) {
		this.point = point;
		this.device = device;
	}

	public Vote(Point point, Device device, Integer vote) {
		this.point = point;
		this.device = device;
		this.vote = vote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Point getPoint() {
		return this.point;
	}

	public void setPoint(Point point) {
		this.point = point;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "did", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Column(name = "vote")
	public Integer getVote() {
		return this.vote;
	}

	public void setVote(Integer vote) {
		this.vote = vote;
	}

}
