USE gasstation;

CREATE TABLE point (id INTEGER PRIMARY KEY AUTO_INCREMENT, lat FLOAT, lon FLOAT, 
					name VARCHAR(256), address VARCHAR(256), worktime VARCHAR(256), 
					state INTEGER NOT NULL DEFAULT 1, 
					modified TIMESTAMP, created TIMESTAMP, 
					isDeleted TINYINT NOT NULL DEFAULT 0, isCardAccepted TINYINT NOT NULL DEFAULT 1, 
					isAccepted TINYINT NOT NULL DEFAULT 0);

CREATE TABLE device (id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(20) UNIQUE);

CREATE TABLE vote (id INTEGER PRIMARY KEY AUTO_INCREMENT, did INTEGER NOT NULL, pid INTEGER NOT NULL, vote INTEGER DEFAULT 0,
FOREIGN KEY (did)
REFERENCES device(id) ON DELETE CASCADE,
FOREIGN KEY (pid)
REFERENCES point(id) ON DELETE CASCADE);

CREATE TABLE types (id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(64));

CREATE TABLE point_types (pid INTEGER, tid INTEGER, price FLOAT DEFAULT 0, modified TIMESTAMP,
FOREIGN KEY (pid)
REFERENCES point(id) ON DELETE CASCADE,
FOREIGN KEY (tid)
REFERENCES types(id) ON DELETE CASCADE,
CONSTRAINT unique_point_types UNIQUE (pid, tid));

CREATE TABLE changes (id INTEGER PRIMARY KEY AUTO_INCREMENT, field INTEGER, did INTEGER, pid INTEGER, created TIMESTAMP, valueNew VARCHAR(256),
FOREIGN KEY (pid)
REFERENCES point(id) ON DELETE CASCADE,
FOREIGN KEY (did)
REFERENCES device(id) ON DELETE CASCADE);
